### ISSUE TITLE
Custom header settings

### ISSUE THREAD

**Issue by Chris-V** [JuanMTech/google_light_theme#1]
Very nice theme!

Custom Header has built-in variables. May I suggest adding those to the theme? It would remove the need to customize through the lovelace config file.

cc: https://maykar.github.io/custom-header/#styling/advanced

Thanks!

**Comment by JuanMTech** [comment]
Indeed. However, when I added the variables directly to the theme, it was not theming properly. So, at the bottom of the `README.md` and the `info.md` files, I added the variables needed so the header would use the correct colors for the theme.
