### ISSUE TITLE
No contrast on Developer Tools / States

### ISSUE THREAD

**Issue by arenasa70** [JuanMTech/google_light_theme#3]
The background on the States list in  the developer tools depends on secondary-background-color.

Changing this value to:

`secondary-background-color: "#EDEDED"`

Will allow the states to be more readable creating the required contrast.  

PD:
The same problem is present on the Google dark theme.  This value will do it there
`secondary-background-color: "#21252D"`

**Comment by JuanMTech** [comment]
Issues corrected on v1.3

**Comment by arenasa70** [comment]
It was fixed on the dark theme, the light theme seems unchanged.
