### ISSUE TITLE
support new theme auto / light / dark features

### ISSUE THREAD

**Issue by civarson** [JuanMTech/google_light_theme#6]
would be really cool to integrate both light and dark themes into one where it can switch automatically as of 0.114.

**Comment by avm99963** [comment]
In my case I could set the light and dark modes to obey my OS dark mode setting by calling the `set_theme` service twice from the developer tools, one time for the light theme and another one for the dark theme (setting each one with its corresponding mode).

Then, I could select "Backend-selected" from my profile and this works fine.

Unfortunately, this method is just for setting the backend theme, so maybe we could research how does the default theme show the configuration selector for auto/light/dark.
